---
- name: Instala o NGINX
  hosts: lab
  become: true  # Become serve pra virar root
  gather_facts: true  # Coleta fatos do sistema, padrao

  tasks:
    - name: Atualiza repo  # Faz um apt update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Instala pacote NGINX
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Cria diretorio NGINX
      ansible.builtin.file:
        path: /var/www/lab
        state: directory
        owner: www-data
        group: www-data
        mode: 0755

